### ISSUE TITLE
Web App Not Working

### ISSUE THREAD

**Issue by AwesomeShare** [Aleksasgrodis/saveddit#26]
Tried it in Chrome, and in Chrome Incognito mode.

I authorized it to use my Reddit account, and it said it was fetching my saved items, but then it went to this link:

https://saveddit.vercel.app/dashboard/all

and nothing was ever displayed in the browser window.  It was just a blank window.

![Snap79](https://user-images.githubusercontent.com/1143972/157954701-2ac73f1e-c668-449d-b77c-5c97bbcdc332.jpg)

**Comment by zinetx** [comment]
Yeah, same thing. Tried other browsers as well.

**Comment by zinetx** [comment]
@Aleksasgrodis Really appreciated.
You're awesome.
Thanks.
